title: Nida Ariqah Wahyu Fatliasputri # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Math Student of Airlangga University 
  <br><br>
  interested in data analytics 
  <br><br>
  <a href="https://www.linkedin.com/in/nida-ariqah-wahyu-fatliasputri-233668146">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
